export type BlogPostNl={slug:string;title:string;query:string;updated:string;intro:string;rows:{when:string;interval:string;wat:string}[];sections:{title:string;text:string}[];faq:{q:string;a:string}[];hreflangEn?:string;related:string[]};
const updated='2026-07-19';

export const postsNl:BlogPostNl[]=[

{slug:'hoe-vaak-kat-ontwormen',title:'Hoe vaak moet je een kat ontwormen?',query:'hoe vaak moet je een kat ontwormen',updated,
intro:'Geen vaste kalendermaand, maar een risico-inschatting. Een binnenkat die nooit een muis ziet, heeft een ander schema nodig dan een buitenkat die jaagt. Hier is hoe je het écht bepaalt — niet hoe vaak de zak ontwormingstabletten toevallig op is.',
rows:[
{when:'Kitten, 3–12 weken',interval:'Om de 2 weken',wat:'Kittens kunnen wormen via de moedermelk krijgen, dus deze fase is strak.'},
{when:'Kitten, 3–6 maanden',interval:'Maandelijks',wat:'Groei en blootstelling nemen toe; het interval schuift naar volwassen ritme.'},
{when:'Volwassen binnenkat',interval:'2 tot 4 keer per jaar',wat:'Lager risico, maar niet nul — vlooien alleen al kunnen lintworm overdragen.'},
{when:'Volwassen buitenkat / jager',interval:'Iedere 1–3 maanden',wat:'Jachtgedrag en contact met prooien verhogen het risico aanzienlijk.'}],
sections:[
{title:'Waarom "elke maand" niet het juiste antwoord is',text:'De meeste kattenbezitters stellen de verkeerde vraag. Niet "hoe vaak moet ik ontwormen", maar "hoeveel risico loopt mijn kat deze maand". Een kat die alleen op het balkon komt, loopt een ander risico dan een kat die drie keer per week een muis binnenbrengt. Dierenartsen werken daarom met risicocategorieën in plaats van één vast interval voor iedere kat.\n\nWat het risico vooral bepaalt: buitentoegang, jachtgedrag, vlooien (die lintworm kunnen overdragen), en contact met andere dieren. Een kat zonder een van deze factoren kan met twee tot vier keer per jaar toe. Een kat met meerdere factoren zit eerder op elke één tot drie maanden.'},
{title:'Wat er gebeurt als je het misdoet',text:'Te vaak ontwormen is zelden gevaarlijk, maar wel onnodig — het is een onbelaste medicatie die je kat toch krijgt. Te weinig ontwormen is het risico waar de meeste adviezen op mikken: een lichte wormbesmetting geeft vaak geen zichtbare symptomen totdat de belasting aanzienlijk is. Gewichtsverlies, een doffe vacht of een opgezette buik bij een kitten zijn late signalen, geen vroege.\n\nHet praktische probleem is zelden de kennis — de meeste eigenaren weten dat ontwormen nodig is. Het probleem is het onthouden van de laatste datum. Zonder een vaste plek waar die datum staat, verschuift "elke drie maanden" al snel naar "ergens dit jaar wel een keer".'},
{title:'Hoe je het schema betrouwbaar maakt',text:'Noteer de exacte datum en het gebruikte middel, niet de maand die je denkt dat het was. Producten verschillen in werkingsduur, en "vorige keer" is geen betrouwbare basis voor de volgende dosis. Een digitale herinnering die automatisch doortelt vanaf de werkelijke datum voorkomt precies het probleem waar de meeste gemiste behandelingen ontstaan: niet onwil, maar een vergeten startpunt.'},
{title:'Welke wormen het vaakst voorkomen, en hoe ze binnenkomen',text:'Spoelwormen zijn de meest voorkomende bij katten en worden opgelopen via jagen, via de moedermelk bij kittens, of gewoon via de grond. Lintworm komt vrijwel altijd via vlooien binnen — de kat slikt tijdens het poetsen een besmette vlo door, wat meteen verklaart waarom een sluitend vlooienschema ook het lintwormrisico verlaagt. Zweepworm en haakworm komen minder vaak voor bij katten in Nederland, maar zijn niet uitgesloten bij katten met veel buitencontact of grondcontact.\n\nDit is meteen waarom "ontwormen" en "vlooienbehandeling" niet los van elkaar te bekijken zijn: een kat die goed beschermd is tegen vlooien, heeft al een aanzienlijk lager lintwormrisico, ook zonder dat daar apart iets voor gedaan wordt.'},
{title:'Signalen die om een tussentijdse controle vragen',text:'Wormen geven bij een lichte besmetting vaak geen zichtbare symptomen — dat is precies wat het risico maakt. Let bij een kat op braken met zichtbare wormen, diarree die aanhoudt, een doffe vacht ondanks normale verzorging, of gewichtsverlies zonder duidelijke oorzaak. Bij kittens is een opgezette buik in combinatie met achterblijvende groei een reden om niet op het volgende geplande moment te wachten, maar direct de dierenarts te bellen.'}],
faq:[
{q:'Moet een binnenkat ook ontwormd worden?',a:'Ja, al is de frequentie lager. Vlooien komen ook bij binnenkatten voor en kunnen lintworm overdragen, dus twee tot vier keer per jaar blijft het gangbare advies.'},
{q:'Kan ik ontwormen en vlooienbehandeling combineren?',a:'Sommige middelen doen beide, andere niet. Controleer het etiket van het specifieke product — combineren zonder te weten wat het middel daadwerkelijk dekt, geeft een vals gevoel van bescherming.'},
{q:'Wat als ik een dosis heb gemist?',a:'Geef de volgende dosis zodra je het merkt en reken vanaf die nieuwe datum verder. Dubbel doseren om in te halen wordt afgeraden.'},
{q:'Kunnen wormen van de kat op mensen overgaan?',a:'Bepaalde wormsoorten zijn in theorie overdraagbaar op mensen, met name bij kinderen die intensief contact hebben en minder hygiënisch zijn. Dit is een van de redenen waarom dierenartsen een regelmatig schema aanraden ook bij een kat die verder gezond oogt.'}],
hreflangEn:'/blog/how-often-worm-cat',
related:['ontwormen-kat-schema','vlooien-bij-de-kat']},

{slug:'hoe-vaak-vlooienbehandeling-hond',title:'Hoe vaak vlooienbehandeling bij de hond?',query:'hoe vaak vlooienbehandeling hond',updated,
intro:'De meeste hondenbezitters denken in maanden. Vlooien denken in weken. Dat verschil in tempo is precies waarom een gemiste behandeling zo snel escaleert van "één keer laat" naar "plaag in huis". Hier is het ritme dat wél werkt.',
rows:[
{when:'Voor de eerste dosis',interval:'Eenmalig',wat:'Controleer minimumleeftijd en gewicht van je hond op het etiket.'},
{when:'Na 4 weken',interval:'Eenmalig',wat:'Bij de meeste maandmiddelen is dit de eerste herhaling.'},
{when:'Doorlopend bij maandmiddelen',interval:'Iedere 4 weken',wat:'Vast op dezelfde weekdag zetten voorkomt uitstel.'},
{when:'Minimaal',interval:'Jaarlijks evalueren',wat:'Seizoen, reizen en leefstijl kunnen het risico en dus het interval veranderen.'}],
sections:[
{title:'De rekenfout die bijna iedereen maakt',text:'Een maandmiddel werkt niet als een schakelaar die na dertig dagen exact uitgaat. De bescherming neemt geleidelijk af richting het einde van de periode, en een paar dagen te laat is meestal geen ramp. Weken te laat is een ander verhaal: de bescherming is dan al een tijd marginaal, en in die periode kan een vlooienpopulatie zich in huis vestigen zonder dat je het ziet.\n\nHet sluipende probleem is dat vlooieneitjes en -larven in tapijt, bank en kieren blijven zitten nadat je de volwassen vlooien niet meer ziet. Tegen de tijd dat je weer vlooien spot, is de omgeving vaak al besmet — en dat kost weken van intensieve behandeling om weer onder controle te krijgen.'},
{title:'Wat écht helpt om het ritme vast te houden',text:'Zet de behandeling op een vaste weekdag, niet op "rond de eerste van de maand" — een specifieke dag is makkelijker te herinneren dan een vage periode. Koop bij voorkeur een meerdoosverpakking, zodat je nooit een dosis mist omdat de vorige op is en je nog naar de winkel moet.\n\nAls je hond zwemt, veel buiten is in een tekengebied, of contact heeft met andere honden op een hondenschool of pension, weegt dat mee in hoe strikt het interval moet zijn. Twijfel je over het juiste middel voor jouw hond en situatie, vraag het gewoon aan de dierenarts — de productkeuze bepaalt namelijk mede het interval.'},
{title:'Als het toch misgaat',text:'Eén gemiste week is meestal geen probleem: geef de eerstvolgende dosis zodra je het merkt en reken vanaf die datum verder. Bij een langere onderbreking — vooral als je al vlooien ziet — is de aanpak breder: behandel de hond én was beddengoed op hoge temperatuur én stofzuig grondig en herhaaldelijk, omdat trilling larven uit hun cocon triggert waar een behandeling ze daarna kan bereiken.'},
{title:'Waarom sommige honden het zwaarder te verduren hebben',text:'Een deel van de honden ontwikkelt een vlooienallergie: al één beet kan dan hevige jeuk, kaalheid en huidontsteking veroorzaken, in schril contrast met een hond die tientallen beten zonder zichtbare reactie doorstaat. Voor deze honden is een sluitend schema geen kwestie van comfort maar van medische noodzaak — een enkele gemiste dosis kan bij hen wél meteen zichtbare gevolgen hebben.\n\nSeizoen speelt ook mee: in warme, vochtige periodes vermeerderen vlooien sneller, en in gebieden met veel tekenrisico is het interval waar sommige eigenaren voor kiezen strikter dan het jaarrond-minimum. Een hond die veel in bos of hoog gras loopt, verdient extra aandacht op precies die momenten.'},
{title:'Wat je in huis merkt voordat je de hond iets ziet',text:'Vlooien zijn vaak eerder zichtbaar aan hun sporen dan aan zichzelf: kleine zwarte korreltjes in de vacht (vlooienpoep) die op vochtig papier een roodbruine vlek achterlaten, is een betrouwbaarder teken dan een levende vlo spotten. Overmatig krabben aan met name de staartbasis en achterpoten is een ander vroeg signaal. Wie dit ziet, behandelt niet alleen de hond maar ook de directe omgeving — de bank, de mand en het tapijt waar de hond het meest ligt.'}],
faq:[
{q:'Is een paar dagen te laat een probleem?',a:'Meestal niet — de bescherming neemt geleidelijk af, dus een paar dagen is zelden kritiek. Weken te laat is anders en verdient extra aandacht.'},
{q:'Moet ik dubbel doseren als ik een behandeling gemist heb?',a:'Nee. Geef een normale dosis zodra je het merkt en tel vanaf die datum verder — dubbel doseren versnelt niets en kan onveilig zijn.'},
{q:'Werkt één behandeling voor het hele huishouden?',a:'Nee, elk dier in huis moet op schema blijven. Eén onbehandeld dier houdt de vlooienpopulatie in stand voor de rest.'},
{q:'Hoe weet ik of mijn hond een vlooienallergie heeft?',a:'Hevige jeuk, kaalheid en huidirritatie die niet in verhouding staan tot het aantal zichtbare vlooien zijn een aanwijzing. Bespreek dit met de dierenarts — voor deze honden is een sluitend schema extra belangrijk.'}],
hreflangEn:'/blog/how-often-flea-treatment-dog',
related:['vlooienbehandeling-hond-schema','ontwormen-hond-schema']},

{slug:'kitten-vaccinatieschema-eerste-jaar',title:'Kitten vaccinatieschema: het complete eerste jaar',query:'kitten vaccinatieschema eerste jaar',updated,
intro:'Het eerste jaar van een kitten zit vol data die je niet uit je hoofd wilt onthouden: vaccinaties, ontworming, en de socialisatieperiode die maar heel kort openstaat. Hier staat de volgorde helder op een rij.',
rows:[
{when:'6–9 weken',interval:'Eerste vaccinatie',wat:'Vaak al gegeven door de fokker of het asiel, samen met de eerste ontworming.'},
{when:'9–12 weken',interval:'Tweede vaccinatie',wat:'Ongeveer 3–4 weken na de eerste dosis.'},
{when:'2–7 weken',interval:'Socialisatieperiode',wat:'De gevoeligste fase voor positieve gewenning aan mensen, geluiden en hantering.'},
{when:'12 maanden',interval:'Jaarlijkse controle',wat:'Overstap naar het volwassen boosterschema.'}],
sections:[
{title:'Waarom de volgorde belangrijker is dan de leeftijd',text:'Maternale antistoffen — bescherming die het kitten van de moeder meekrijgt — vervagen op een onvoorspelbaar tempo. Daarom worden vaccinaties in doses gegeven in plaats van in één keer: elke dosis vangt het moment op waarop de eerdere bescherming begint weg te vallen. Een kitten dat te vroeg of te laat begint, doorloopt gewoon dezelfde reeks vanaf het eigen startpunt — de dierenarts past het schema aan op de werkelijke begindatum, niet op een kalenderleeftijd.\n\nDe socialisatieperiode loopt voor kittens grotendeels af rond 7 weken, wat een van de redenen is waarom fokkers en asielen al vóór het herplaatsen zoveel mogelijk positieve hantering inbouwen. Na deze periode blijft wennen mogelijk, maar minder vanzelfsprekend.'},
{title:'Wat er gelijktijdig loopt naast de vaccinaties',text:'Ontworming volgt in het begin een strakker ritme dan vaccinatie: elke twee weken zolang het kitten heel jong is, omdat kittens al vóór de geboorte of via de melk wormen kunnen oplopen. Rond drie tot zes maanden schuift dit naar een maandelijks ritme, en vlooienbehandeling start doorgaans zodra het kitten de minimumleeftijd en het minimumgewicht van een product haalt — controleer dit op het etiket, niet op een vuistregel.\n\nDeze parallelle schema’s zijn precies waarom het eerste jaar overweldigend kan aanvoelen: er lopen op elk moment twee of drie schema’s tegelijk, elk met een eigen interval.'},
{title:'Wat een gemiste dosis betekent',text:'Een gemiste vaccinatiedosis betekent niet automatisch dat de hele reeks opnieuw moet, maar het kan wel betekenen dat de opgebouwde bescherming niet meer volledig betrouwbaar is. Neem bij twijfel contact op met de dierenarts en geef de laatst bevestigde datum door — die datum bepaalt hoe wordt hervat, niet een schatting.'},
{title:'Wat er nog meer bij een goede start hoort',text:'Rond de eerste vaccinatieronde adviseren veel dierenartsen ook een test op FIV en FeLV, twee virussen die het immuunsysteem van de kat blijvend kunnen aantasten — vooral relevant bij een kitten met onbekende afkomst of uit een omgeving met veel andere katten. Deze test is los van het vaccinatieschema, maar wordt vaak op hetzelfde consult meegenomen omdat het kitten er toch al is.\n\nDe castratie- of sterilisatiedatum ligt meestal rond vijf tot zes maanden, maar de dierenarts bepaalt de precieze timing op basis van gewicht en ontwikkeling, niet alleen leeftijd. Dit gesprek begint doorgaans rond de laatste vaccinatieronde.'},
{title:'Socialisatie: wat wel en niet helpt',text:'Positieve, korte, herhaalde blootstelling werkt beter dan één lange, overweldigende ervaring. Laat het kitten in de socialisatieperiode rustig kennismaken met verschillende geluiden, oppervlakken en mensen — zonder te forceren. Een kitten dat zich op een moment onttrekt, hoeft niet "doorgezet" te worden; een volgende korte, rustige poging werkt beter dan aandringen.'}],
faq:[
{q:'Kan de eerste vaccinatie later dan 6 weken?',a:'Ja, veel kittens beginnen later afhankelijk van wanneer ze herplaatst zijn. De dierenarts stemt de rest van de reeks af op de werkelijke startdatum.'},
{q:'Moet een binnenkitten hetzelfde schema volgen?',a:'De basisreeks vaccinaties wordt over het algemeen wel geadviseerd, ongeacht buitentoegang. Het volwassen onderhoudsschema kan later lichter zijn voor een kitten dat binnen blijft.'},
{q:'Wat als de voorgeschiedenis van het kitten onbekend is?',a:'Behandel de vaccinatie- en ontwormingsgeschiedenis als onbekend en laat de dierenarts opnieuw beginnen of aanpassen — ga niet uit van een schema dat mogelijk niet is gevolgd.'},
{q:'Is een FIV/FeLV-test verplicht?',a:'Nee, maar het wordt vaak geadviseerd bij een kitten met onbekende afkomst of veel contact met andere katten. Bespreek dit bij de eerste vaccinatieafspraak.'},
{q:'Wanneer krijgt mijn kitten de eerste jaarlijkse booster?',a:'Meestal rond twaalf maanden, na afronding van de kittenreeks — vanaf dat moment gaat het kitten over op het volwassen onderhoudsschema, waarvan de precieze frequentie per vaccin verschilt.'}],
hreflangEn:'/guides/kitten-first-year-schedule',
related:['kitten-vaccinatieschema','ontwormen-kat-schema']},

{slug:'puppy-vaccinatieschema-eerste-jaar',title:'Puppy vaccinatieschema: het complete eerste jaar',query:'puppy vaccinatieschema eerste jaar',updated,
intro:'Het eerste levensjaar van een puppy stapelt meer medische en gedragsmatige mijlpalen op elkaar dan enig ander jaar. Vaccinaties, ontworming, de socialisatieperiode en het gesprek over castratie — allemaal binnen twaalf maanden. Hier is de volgorde.',
rows:[
{when:'6–8 weken',interval:'Eerste vaccinatie',wat:'Vaak al gegeven door de fokker, samen met de eerste ontworming en een gezondheidscheck.'},
{when:'10–12 weken',interval:'Tweede vaccinatie',wat:'Ongeveer 2–4 weken na de eerste dosis.'},
{when:'14–16 weken',interval:'Derde vaccinatie',wat:'Vaak inclusief rabiës waar verplicht; volledige buitentoegang begint doorgaans hierna.'},
{when:'12–16 weken',interval:'Socialisatieperiode',wat:'De gevoeligste fase voor positieve gewenning aan mensen, geluiden en andere dieren.'}],
sections:[
{title:'Waarom deze reeks niet te versnellen is',text:'Net als bij kittens vervagen de antistoffen die een puppy van de moeder meekrijgt op een tempo dat per dier verschilt. De drie doses zijn zo gepland dat elke volgende dosis het gat opvangt waar de vorige bescherming wegvalt. Vervroegen lost dus niets op — het risico is juist dat een dosis samenvalt met een periode waarin de maternale antistoffen de vaccinrespons nog dempen.\n\nDe socialisatieperiode van 12 tot 16 weken overlapt bewust met de laatste vaccinatierondes, wat lastig kan voelen: veel dierenartsen adviseren inmiddels voorzichtige, begeleide sociale blootstelling vóór de reeks volledig is afgerond, in plaats van te wachten tot na de laatste dosis — vraag hier expliciet naar bij je dierenarts.'},
{title:'Wat er tegelijkertijd loopt',text:'Ontworming volgt een strakker ritme in de eerste weken: elke twee weken zolang de puppy heel jong is, omdat een puppy al voor de geboorte wormen van de moeder kan oplopen. Rond drie tot zes maanden schuift dit naar maandelijks. Vlooien- en tekenbehandeling starten doorgaans zodra de puppy de minimumleeftijd en het minimumgewicht van een product bereikt.\n\nRond zes tot twaalf maanden komt daar het gesprek over castratie bij, waarvan de timing sterk verschilt per ras en formaat — met name bij grote rassen is hier de afgelopen jaren voorzichtiger advies over gekomen. Dit is geen vaste datum maar een gesprek met de dierenarts.'},
{title:'De praktijk: waarom bijhouden meer oplevert dan onthouden',text:'Het eerste jaar bevat zoveel opeenvolgende data dat het geheugen alleen onbetrouwbaar wordt zodra er iets tussenkomt — een verhuizing, een drukke week, een tweede puppy erbij. Een record dat automatisch de volgende datum berekent vanaf de laatst geregistreerde, haalt precies dat rekenwerk weg op het moment dat een eigenaar er het minste tijd voor heeft.'},
{title:'Puppycursus en kennelhoest: wat erbij komt kijken',text:'Veel puppycursussen en pensions eisen een aparte kennelhoestvaccinatie, los van de kernvaccinaties — plan deze op tijd als je van plan bent naar een cursus of oppas te gaan, want de bescherming heeft na toediening enige tijd nodig om op te bouwen. Een puppycursus vóór de volledige vaccinatiereeks is klaar, kan alsnog verantwoord als de locatie werkt met een gecontroleerde groep gevaccineerde puppy’s — vraag dit expliciet na voordat je inschrijft.\n\nHet is een van de weinige momenten waarop vaccinatieplanning en gedragsplanning elkaar direct raken: te lang wachten met sociale blootstelling om "veilig" te zijn, kan gedragsmatig een prijs hebben die net zo reëel is als een medisch risico.'},
{title:'Wat opvalt bij grotere en kleinere rassen',text:'Grote en reuzenrassen groeien sneller in hun eerste jaar en hebben vaker aangepast advies over voeding en groeitempo naast het vaccinatieschema — snel groeien kan gewrichtsproblemen op latere leeftijd beïnvloeden. Kleine rassen bereiken juist eerder hun volwassen gewicht, wat meespeelt bij de timing van castratie en de overstap naar volwassen voeding. Het vaccinatieschema zelf verschilt niet fundamenteel per formaat, maar de gesprekken eromheen wel.'}],
faq:[
{q:'Kan de puppyreeks later beginnen dan 6–8 weken?',a:'Ja, de dierenarts stemt de hele reeks af op de werkelijke startdatum, niet op een vaste kalenderleeftijd.'},
{q:'Is de socialisatieperiode echt zo strikt?',a:'Het is een gevoelige periode, geen harde grens — gewenning erna blijft waardevol, maar wordt over het algemeen als minder vormend beschouwd voor het gedrag op lange termijn.'},
{q:'Wanneer moet ik castratie ter sprake brengen?',a:'Rond zes maanden is een gangbaar moment om dit gesprek te starten, maar de timing verschilt per ras, formaat en individuele gezondheid — laat de dierenarts adviseren.'},
{q:'Heeft mijn puppy een kennelhoestvaccinatie nodig?',a:'Alleen als je een puppycursus, pension of ander groepscontact plant — dit is geen kernvaccinatie maar wordt vaak wel geëist door die locaties. Plan het ruim op tijd.'}],
hreflangEn:'/guides/puppy-first-year-schedule',
related:['vlooienbehandeling-hond-schema','ontwormen-hond-schema']},

{slug:'vlooien-bij-de-kat',title:'Vlooien bij de kat: behandeling en schema',query:'vlooien bij de kat behandeling en schema',updated,
intro:'Katten poetsen bewijs weg. Dat is het probleem. Een kat kan al weken vlooien meedragen voordat je er ook maar één ziet — tegen die tijd zitten de eitjes al in het tapijt. Zo pak je het aan, en zo hou je het onder controle.',
rows:[
{when:'Voor de eerste dosis',interval:'Eenmalig',wat:'Controleer minimumleeftijd en gewicht van de kat op het etiket.'},
{when:'Na 4 weken',interval:'Eenmalig',wat:'Bij de meeste maandmiddelen is dit de eerste herhaling.'},
{when:'Doorlopend bij maandmiddelen',interval:'Iedere 4 weken',wat:'Vast op dezelfde datum zetten voorkomt geleidelijk uitstel.'},
{when:'Minimaal',interval:'Jaarlijks evalueren',wat:'Buitentoegang en seizoen bepalen of het interval moet verstrakken.'}],
sections:[
{title:'Waarom je een vlooienprobleem meestal te laat ziet',text:'Een volwassen vlooienpopulatie op je kat is eigenlijk het topje van de ijsberg. Van alle vlooien, eitjes, larven en poppen die zich in en rond je huis bevinden, is slechts een klein deel de volwassen vlo die je daadwerkelijk ziet — de rest zit onzichtbaar in tapijt, kieren en beddengoed. Poppen zijn daarbij het hardnekkigst: ze zitten beschermd in een cocon, zijn bestand tegen veel insecticiden, en kunnen maandenlang wachten tot trilling of warmte ze triggert om uit te komen.\n\nOmdat katten zichzelf grondig poetsen, zie je vaak geen vlooien terwijl de omgeving allang besmet is. Tegen de tijd dat je wél vlooien spot — of je kat overmatig krabt — is de kans groot dat de eitjes en larven zich al door huis hebben verspreid.'},
{title:'De juiste aanpak als je vlooien vindt',text:'Behandel eerst alle dieren in huis, niet alleen de kat waar je vlooien op zag — anders cirkelt de populatie simpelweg tussen de dieren heen en weer, inclusief "de kat die nooit vlooien heeft". Was beddengoed op minstens 60 graden en stofzuig grondig en herhaaldelijk: de trilling van de stofzuiger triggert poppen om uit te komen, waarna een behandeling ze daadwerkelijk kan bereiken. Gooi de stofzuigerzak daarna direct buiten leeg.\n\nBij een zichtbare plaag is een omgevingsspray voor tapijt en plinten vaak nodig naast de behandeling van de dieren zelf — alleen het dier behandelen lost de indoor-populatie niet op.'},
{title:'Hoe je het daarna voorkomt',text:'Consistentie is de enige echte preventie. Zet de behandeling op een vaste datum in plaats van "rond het begin van de maand" — een specifieke dag onthoud je beter dan een vage periode. Een meerdoosverpakking voorkomt dat je een dosis mist omdat de vorige op is. En noteer de werkelijke toedieningsdatum, niet de datum die je denkt dat het was — bij twijfel over de laatste dosis is een dierenarts de juiste vraagbaak, niet een gok.'},
{title:'Waarom "natuurlijke" middelen voorzichtig moeten worden gebruikt',text:'Katten zijn opvallend gevoelig voor stoffen die voor honden en mensen onschuldig zijn — bepaalde etherische oliën en sommige plantaardige middelen kunnen bij katten leverproblemen of ernstigere reacties veroorzaken. "Natuurlijk" betekent bij katten niet automatisch "veilig". Overleg elk alternatief middel eerst met de dierenarts, zeker als het via de huid wordt toegepast, aangezien katten dit bij het poetsen alsnog binnenkrijgen.\n\nHetzelfde voorzichtigheidsprincipe geldt voor hondenmiddelen: sommige vlooienproducten voor honden bevatten stoffen die voor katten giftig zijn. Gebruik nooit een hondenproduct bij een kat, ook niet "in noodgeval" of in een lagere dosis.'},
{title:'De levenscyclus in cijfers',text:'Eén volwassen vrouwtjesvlo legt dagelijks tientallen eitjes, die overal vanaf de kat vallen — op de bank, in de mand, in de auto. Binnen enkele dagen tot weken komen hier larven uit die zich voeden met organisch materiaal in tapijt en kieren, voordat ze verpoppen. De pop is de fase die het langst standhoudt: weken tot maanden, wachtend op trilling of warmte om uit te komen als volwassen vlo. Dit verklaart waarom een huis "plotseling" weer vlooien lijkt te hebben nadat het weken stil was — de poppen wachtten simpelweg op het juiste moment.'}],
faq:[
{q:'Kan een binnenkat ook vlooien krijgen?',a:'Ja. Vlooien komen ook binnen via andere huisdieren, bezoek of kleding, dus binnenkatten blijven kwetsbaar, al is het risico lager dan bij buitenkatten.'},
{q:'Hoe lang duurt het om een plaag onder controle te krijgen?',a:'Vaak enkele maanden van consistente behandeling, omdat poppen in tapijt bestand zijn tegen veel middelen en in golven uitkomen.'},
{q:'Moet ik dubbel doseren na een gemiste behandeling?',a:'Nee. Geef een normale dosis zodra je het merkt en reken vanaf die datum verder — dubbel doseren is niet veiliger en lost niets sneller op.'},
{q:'Kan ik een hondenmiddel bij mijn kat gebruiken?',a:'Nee, nooit. Sommige stoffen in hondenvlooienproducten zijn giftig voor katten, ook in kleine hoeveelheden. Gebruik uitsluitend producten die specifiek voor katten zijn geregistreerd.'}],
hreflangEn:'/schedules/cat-flea-treatment-schedule',
related:['vlooien-kat-schema','ontwormen-kat-schema']}
];

export const postNl=(slug:string)=>postsNl.find(item=>item.slug===slug);
for(const item of postsNl){const chars=[item.intro,...item.sections.flatMap(s=>[s.title,s.text]),...item.faq.flatMap(f=>[f.q,f.a])].join(' ').trim().length;if(chars<4000||item.rows.length<4||item.faq.length<3||item.related.length<2)throw new Error(`NL blog quality gate failed for ${item.slug}: ${chars} chars`)}
