export type Guide={slug:string;species:string;title:string;query:string;updated:string;intro:string;rows:{when:string;interval:string;what:string}[];why:string;missed:string;caveat:string;guide:string;faq:{q:string;a:string}[];blogs:string[];siblings:string[]};
const updated='2026-07-19';

export const guides:Guide[]=[
{slug:'puppy-first-year-schedule',species:'Puppy',title:'Puppy first year schedule',query:'puppy first year schedule',updated,
intro:'A puppy’s first twelve months compress more medical, behavioural and physical change than any other stage of a dog’s life. This guide lays out the whole year in order — vaccinations, worming, socialisation, neutering conversations and growth checks — so nothing falls through the gap between a busy new-owner schedule and a vet visit six months away.',
rows:[
{when:'6–8 weeks',interval:'Before rehoming, usually by the breeder',what:'First vaccination and first deworming, plus a general health check and weighing.'},
{when:'10–12 weeks',interval:'~2–4 weeks after dose one',what:'Second vaccination; many practices allow supervised outdoor exposure a week or so after this dose — confirm your vet’s local advice.'},
{when:'14–16 weeks',interval:'~2–4 weeks after dose two',what:'Third vaccination, often including rabies where required; full outdoor access typically begins here.'},
{when:'12–16 weeks',interval:'Socialisation window',what:'The period behaviourists consider most sensitive for positive exposure to people, sounds, surfaces and other animals.'},
{when:'2–12 weeks old',interval:'Every 2 weeks',what:'Worming continues on a fortnightly rhythm while the puppy is still very young.'},
{when:'3–6 months old',interval:'Monthly',what:'Worming moves to a monthly interval; flea and tick prevention usually starts once the puppy meets a product’s minimum age and weight.'},
{when:'6–12 months',interval:'Vet-guided',what:'Spay/neuter timing conversation, adult booster planning, and a mid-year weight and growth check.'},
{when:'12 months',interval:'Once',what:'First annual health check and the switch onto an adult booster and prevention schedule.'}],
why:'A puppy’s immune system, body weight and behaviour all change fast enough that a single fixed date does not work the way it does for an adult dog. Vaccine doses are spaced to work with (not against) maternal antibodies that fade unpredictably in the first weeks of life, worming intervals shorten because young puppies carry a much higher parasite burden, and the socialisation window closes around 12–16 weeks regardless of vaccination status — so vets increasingly recommend careful, supervised exposure before the course finishes rather than waiting for full immunity. Recording exact dates in the first year matters more than in any later year because so many of these events are sequential: one step’s timing depends on the one before it.',
missed:'A missed puppy vaccination dose does not always mean starting the whole course again, but it can extend the gap before full protection and change the next appointment date — only your vet can say which for the specific vaccine used. A missed worming date in a young puppy is lower-stakes but still worth catching up promptly, since puppies can carry a heavier worm burden than adults. Write down the actual date something happened, not the week you think it happened; puppy schedules move fast enough that memory alone is unreliable within a month.',
caveat:'This guide sequences the commonly used milestones for a healthy puppy in a low-risk environment; it is not a substitute for your veterinarian’s specific protocol, which will vary by vaccine brand, breed, local disease prevalence and the puppy’s own health. Toy breeds, giant breeds, rescue puppies with unknown history, and puppies showing any illness should follow their vet’s individual plan instead of this general timeline. Seek prompt veterinary advice for vomiting, diarrhoea, lethargy, reduced appetite or any sudden behaviour change.',
guide:'The most useful way to use a first-year timeline is to log each event the day it happens rather than trying to reconstruct it later from memory or a paper vaccination card that can go missing.\n\nBecause so many puppy milestones depend on the date of the one before it, a record that calculates the next due date automatically removes the mental math of "second dose was three weeks ago, so third dose is around…" — which matters most in exactly the busy, sleep-deprived first months of puppy ownership when it is easiest to lose track.',
faq:[
{q:'Can I start the puppy vaccination series later than 6–8 weeks?',a:'Yes, many puppies begin later depending on when they were rehomed or their individual health; your vet will adjust the whole sequence around the actual start date rather than the age given here.'},
{q:'Is the 12–16 week socialisation window really that strict?',a:'Behaviourists treat it as a sensitive period rather than a hard cutoff — exposure after it is still valuable, but is generally considered less effective at shaping lifelong temperament.'},
{q:'When should I ask about neutering?',a:'Timing varies significantly by breed size and individual health, and recommendations have shifted in recent years, particularly for larger breeds — this is a conversation to have with your vet around the 6-month mark rather than a fixed date to follow.'}],
blogs:['dog-vaccination-schedule','annual-pet-care-costs'],
siblings:['kitten-first-year-schedule','senior-dog-care-schedule']},

{slug:'kitten-first-year-schedule',species:'Kitten',title:'Kitten first year schedule',query:'kitten first year schedule',updated,
intro:'A kitten’s first year moves through vaccination courses, a fast-changing worming rhythm, a socialisation window, and a neutering decision — usually inside twelve months that also include the biggest jump in size and behaviour a cat will ever go through. This guide lays the year out in order so a new kitten owner can see what is coming next.',
rows:[
{when:'6–9 weeks',interval:'Before rehoming, usually by the breeder or shelter',what:'First vaccination dose and first deworming, alongside a general health check.'},
{when:'9–12 weeks',interval:'~3–4 weeks after dose one',what:'Second vaccination; core protection typically builds meaningfully after this dose, but confirm timing with your vet before unsupervised outdoor access.'},
{when:'2–12 weeks old',interval:'Every 2 weeks',what:'Worming continues fortnightly while the kitten is very young, since kittens can carry worms from birth or through milk.'},
{when:'2–7 weeks old',interval:'Socialisation window',what:'The period considered most sensitive for positive exposure to handling, other animals and everyday household sounds.'},
{when:'3–6 months old',interval:'Monthly',what:'Worming moves to monthly; flea prevention typically starts once the kitten clears a product’s minimum age and weight — check the label, not just the calendar.'},
{when:'4–6 months',interval:'Vet-guided',what:'Spay/neuter timing conversation — commonly discussed around this age, but confirmed by your vet for the individual kitten.'},
{when:'12 months',interval:'Once',what:'First annual health check and the move onto an adult booster and prevention schedule.'}],
why:'Kittens carry a heavier early parasite and vaccine-timing dependency than adult cats because maternal antibody levels are unpredictable and fade at different rates animal to animal, which is why the early vaccine doses are spaced rather than given all at once. The socialisation window for cats closes earlier than for dogs — often cited as ending around 7 weeks — which is one reason breeders and shelters front-load a great deal of handling before a kitten is even rehomed. Because an indoor-only kitten’s risk profile differs sharply from one with any outdoor access, the exact worming and flea interval a vet recommends after the first year can vary more than the fixed first-year course does.',
missed:'A missed kitten vaccination dose can change how much protection has actually built up and may change your vet’s recommended next date — confirm with the practice rather than assuming the original schedule still applies. A missed worming date at this age is common and usually low-stakes to catch up on promptly. As with puppies, write the exact date down; a kitten’s early schedule compresses enough milestones into a few months that "sometime last month" is not precise enough to plan around.',
caveat:'This is a general sequence for a healthy kitten in a typical household, not an individual veterinary protocol. Bottle-raised kittens, kittens with unknown history from a rescue, and any kitten showing illness should follow their vet’s specific plan instead. Seek prompt veterinary advice for vomiting, diarrhoea, lethargy, reduced appetite, or if a kitten stops growing at the expected rate.',
guide:'Because the kitten year has more density in its first four months than any other stretch of a cat’s life, the most reliable way to stay on top of it is logging each event on the day it happens rather than relying on a shelter’s printed card, which can be misplaced during the move into a new home.\n\nA record that automatically calculates the next due date from the last logged one removes the guesswork of tracking multiple overlapping fortnightly and monthly intervals at once — which is exactly when new kitten owners are least likely to have the mental bandwidth for manual tracking.',
faq:[
{q:'Do indoor-only kittens need the same schedule?',a:'The vaccination and early worming course is generally recommended regardless of indoor status; ongoing adult-year flea and worming frequency is where indoor-only cats often move to a lighter schedule, decided with your vet.'},
{q:'Why does the socialisation window close so early for kittens?',a:'It is generally considered to close earlier than a puppy’s, which is why breeders and shelters concentrate handling and exposure before a kitten is typically rehomed at 8–12 weeks.'},
{q:'What if my kitten came from an unknown background?',a:'Treat the vaccination and worming history as unknown and let your vet restart or adjust the course — do not assume any prior treatment happened on schedule.'}],
blogs:['cat-vaccination-schedule','how-often-worm-cat'],
siblings:['puppy-first-year-schedule','senior-dog-care-schedule']},

{slug:'senior-dog-care-schedule',species:'Senior dog',title:'Senior dog care schedule',query:'senior dog care schedule',updated,
intro:'A dog does not become "senior" on a single birthday — the transition depends heavily on breed and size, with giant breeds reaching senior status years before small breeds. This guide covers what changes once a dog crosses into that stage: more frequent vet visits, a closer eye on weight and mobility, and medication or supplement reviews that a once-a-year check-up can miss.',
rows:[
{when:'Senior-life transition',interval:'Breed-and-size dependent',what:'Ask your vet when your specific dog is considered senior — commonly earlier for giant breeds, later for small breeds.'},
{when:'Vet check-ups',interval:'Every 6 months once senior',what:'Twice-yearly visits catch age-related change between what an annual visit alone would show.'},
{when:'Bloodwork and urinalysis',interval:'Annually, or as advised',what:'Baseline senior bloodwork helps a vet spot kidney, liver or thyroid changes earlier by comparing against the dog’s own prior results.'},
{when:'Weight check',interval:'Monthly at home',what:'Both weight loss and weight gain in a senior dog are worth flagging — track it rather than relying on visual impression.'},
{when:'Dental review',interval:'At every vet visit',what:'Dental disease is common in older dogs and is frequently underestimated without a professional look.'},
{when:'Mobility and joint check',interval:'Ongoing, at home',what:'Watch for stiffness after rest, reluctance on stairs, or slower rising — flag changes rather than assuming they are simply "getting old".'},
{when:'Medication review',interval:'At every vet visit',what:'Any ongoing medication or supplement should be reviewed as kidney and liver function change with age.'}],
why:'Ageing changes a dog’s baseline gradually enough that changes are easy to miss without a consistent comparison point — which is exactly what regular bloodwork and weight logs provide. Moving from annual to twice-yearly vet visits roughly doubles the number of chances to catch a developing issue while it is still manageable, since many senior conditions (kidney disease, early arthritis, dental disease) progress silently for months before becoming visible day to day. Breed size drives a large part of the timeline: giant breeds often enter their senior years by 6, while small breeds may not be considered senior until 10 or later.',
missed:'A missed senior check-up is a bigger gap than it would be for a younger dog, because six months is long enough for a slow-developing condition to progress from early and manageable to advanced. If a check-up is overdue, book the next available appointment rather than waiting for the "proper" six-month mark to come around again. A missed weight-log entry is lower stakes, but gaps longer than a month or two make it harder to spot a gradual trend versus normal week-to-week fluctuation.',
caveat:'This schedule is a general framework, not a diagnosis or treatment plan — an individual senior dog with an existing condition will need a plan built around that condition specifically. Seek prompt veterinary advice for sudden weight loss, laboured breathing, collapse, seizures, a distended abdomen, or any rapid behaviour change, none of which should wait for a scheduled visit.',
guide:'A senior dog’s record becomes more valuable the longer it runs, because the real signal is the trend — this month’s weight compared to six months ago, this year’s bloodwork compared to last year’s — not any single reading in isolation.\n\nKeeping vet visits, weight checks and medication reviews on one running record makes it far easier to bring a complete picture to each appointment, rather than trying to recall from memory whether a symptom is new or has been present for months.',
faq:[
{q:'At what age is a dog considered senior?',a:'It depends heavily on breed size — giant breeds are often considered senior by around 6, medium breeds around 7–8, and small breeds sometimes not until 10 or later. Ask your vet for guidance specific to your dog.'},
{q:'Why twice-yearly visits instead of annual?',a:'Six months is roughly how long many age-related conditions can progress from early-stage to harder-to-manage without being noticed day to day at home.'},
{q:'Is weight gain or weight loss more concerning in a senior dog?',a:'Both are worth flagging to a vet — unexplained change in either direction can signal something worth investigating rather than being dismissed as normal ageing.'}],
blogs:['annual-pet-care-costs','dog-vaccination-schedule'],
siblings:['puppy-first-year-schedule','kitten-first-year-schedule']}
];

export const guide=(slug:string)=>guides.find(item=>item.slug===slug);
for(const item of guides){const words=[item.intro,item.why,item.missed,item.caveat,item.guide,...item.faq.flatMap(f=>[f.q,f.a])].join(' ').trim().split(/\s+/).length;if(words<350||item.rows.length<4||item.faq.length<3||item.blogs.length<2||item.siblings.length<2)throw new Error(`SEO quality gate failed for ${item.slug}: ${words} words`)}
