export type ProductSpecies='dog'|'cat'|'both';
export type Product={name:string;species:ProductSpecies;type:'flea_tick'|'worming'|'heartworm'|'vaccination'|'medication';intervalDays:number;notes:string;warning?:string};

// Curated label intervals are planning defaults, never veterinary advice.
export const products:Product[]=[
 {name:'Bravecto chew',species:'dog',type:'flea_tick',intervalDays:84,notes:'Every 12 weeks per label.'},
 {name:'Bravecto Plus cat',species:'cat',type:'flea_tick',intervalDays:56,notes:'Every 8 weeks per label.'},
 {name:'Bravecto spot-on dog',species:'dog',type:'flea_tick',intervalDays:84,notes:'Every 12 weeks per label.'},
 {name:'Frontline Plus dog',species:'dog',type:'flea_tick',intervalDays:28,notes:'Usually every 4 weeks per label.'},
 {name:'Frontline Plus cat',species:'cat',type:'flea_tick',intervalDays:28,notes:'Usually every 4 weeks per label.'},
 {name:'Advantage dog',species:'dog',type:'flea_tick',intervalDays:28,notes:'Usually every 4 weeks per label.'},
 {name:'Advantage cat',species:'cat',type:'flea_tick',intervalDays:28,notes:'Usually every 4 weeks per label.'},
 {name:'Advocate dog',species:'dog',type:'heartworm',intervalDays:28,notes:'Usually every 4 weeks per label.'},
 {name:'Advocate cat',species:'cat',type:'heartworm',intervalDays:28,notes:'Usually every 4 weeks per label.'},
 {name:'Stronghold dog',species:'dog',type:'flea_tick',intervalDays:28,notes:'Usually every 4 weeks per label.'},
 {name:'Stronghold cat',species:'cat',type:'flea_tick',intervalDays:28,notes:'Usually every 4 weeks per label.'},
 {name:'Seresto dog collar',species:'dog',type:'flea_tick',intervalDays:240,notes:'Up to 8 months per label.'},
 {name:'Seresto cat collar',species:'cat',type:'flea_tick',intervalDays:240,notes:'Up to 8 months per label.'},
 {name:'Milbemax dog',species:'dog',type:'worming',intervalDays:90,notes:'Quarterly is a common planning interval.'},
 {name:'Milbemax cat',species:'cat',type:'worming',intervalDays:90,notes:'Quarterly is a common planning interval.'},
 {name:'Drontal dog',species:'dog',type:'worming',intervalDays:90,notes:'Follow the label and your vet.'},
 {name:'Drontal cat',species:'cat',type:'worming',intervalDays:90,notes:'Follow the label and your vet.'},
 {name:'Panacur dog',species:'dog',type:'worming',intervalDays:90,notes:'Course length varies by indication.'},
 {name:'Panacur cat',species:'cat',type:'worming',intervalDays:90,notes:'Course length varies by indication.'},
 {name:'NexGard dog',species:'dog',type:'flea_tick',intervalDays:30,notes:'Monthly per label.'},
 {name:'NexGard Spectra dog',species:'dog',type:'heartworm',intervalDays:30,notes:'Monthly per label.'},
 {name:'Simparica dog',species:'dog',type:'flea_tick',intervalDays:35,notes:'Monthly per label.'},
 {name:'Simparica Trio dog',species:'dog',type:'heartworm',intervalDays:35,notes:'Monthly per label.'},
 {name:'Credelio dog',species:'dog',type:'flea_tick',intervalDays:30,notes:'Monthly per label.'},
 {name:'Credelio cat',species:'cat',type:'flea_tick',intervalDays:30,notes:'Monthly per label.'},
 {name:'Revolution Plus cat',species:'cat',type:'heartworm',intervalDays:30,notes:'Monthly per label.'},
 {name:'Interceptor Plus dog',species:'dog',type:'heartworm',intervalDays:30,notes:'Monthly per label.'},
 {name:'Trifexis dog',species:'dog',type:'heartworm',intervalDays:30,notes:'Monthly per label.'},
 {name:'K9 Advantix dog',species:'dog',type:'flea_tick',intervalDays:28,notes:'Dog-only formula.'},
 {name:'Vectra 3D dog',species:'dog',type:'flea_tick',intervalDays:28,notes:'Dog-only formula.'},
 {name:'Vectra Felis cat',species:'cat',type:'flea_tick',intervalDays:28,notes:'Cat-specific formula.'},
 {name:'Rabies vaccine',species:'both',type:'vaccination',intervalDays:365,notes:'Booster timing is vet- and jurisdiction-specific.'},
 {name:'Core dog vaccine',species:'dog',type:'vaccination',intervalDays:365,notes:'Booster timing is vet-specific.'},
 {name:'Core cat vaccine',species:'cat',type:'vaccination',intervalDays:365,notes:'Booster timing is vet-specific.'},
 {name:'Lepto vaccine dog',species:'dog',type:'vaccination',intervalDays:365,notes:'Booster timing is vet-specific.'},
 {name:'Kennel cough vaccine dog',species:'dog',type:'vaccination',intervalDays:365,notes:'Booster timing is vet-specific.'},
 {name:'FeLV vaccine cat',species:'cat',type:'vaccination',intervalDays:365,notes:'Booster timing is vet-specific.'},
 {name:'Heartgard dog',species:'dog',type:'heartworm',intervalDays:30,notes:'Monthly per label.'},
 {name:'Feliway is not a medicine',species:'cat',type:'medication',intervalDays:30,notes:'Not a treatment; use this only as a personal reminder.',warning:'Check with your vet before recording a medication.'},
];
export function productFor(name:string){return products.find(product=>product.name===name)}
