export type Schedule = {slug:string;species:string;treatment:string;intro:string;rows:{when:string;interval:string;what:string}[];why:string;missed:string;caveat:string;faq:{q:string;a:string}[];blogs:string[];siblings:string[]};
const common=(species:string,treatment:string,interval:string):Pick<Schedule,'intro'|'rows'|'why'|'missed'|'caveat'|'faq'>=>({intro:`A practical ${treatment.toLowerCase()} reference for ${species.toLowerCase()} owners. Your veterinarian and product label always set the final dates.`,rows:[{when:'Starting point',interval,what:`Record the first ${treatment.toLowerCase()} date and product.`},{when:'Ongoing care',interval,what:'Repeat on the veterinarian-approved interval.'},{when:'Annual review',interval:'Every year',what:'Review risk, health, product and timing with your vet.'}],why:`The ${interval.toLowerCase()} rhythm reflects how long protection or clinical guidance normally lasts. Product, age, lifestyle and local disease risk can change it.`,missed:'Do not double a dose. Check the product instructions and contact your veterinarian when a vaccination or medicine is overdue; some courses may need to be restarted.',caveat:'This page is a planning reference, not individual veterinary advice. Young, pregnant, ill or immunocompromised pets need a veterinarian-set plan.',faq:[{q:`How often does a ${species.toLowerCase()} need ${treatment.toLowerCase()}?`,a:`The usual reference interval is ${interval.toLowerCase()}, but follow your veterinarian and the exact product label.`},{q:'What if the date is missed?',a:'Give no double dose. Check the label and ask your veterinarian how to restart safely.'},{q:'Can the schedule change?',a:'Yes. Age, health, travel, geography, exposure and product choice can all change the right interval.'}]});
const make=(slug:string,species:string,treatment:string,interval:string,blogs:string[],siblings:string[]):Schedule=>({slug,species,treatment,...common(species,treatment,interval),blogs,siblings});
export const schedules:Schedule[]=[
make('dog-flea-treatment-schedule','Dog','Flea treatment','Every 30 days',['how-often-flea-treatment-dog','missed-flea-treatment'],['dog-worming-schedule','adult-dog-booster-schedule']),
make('puppy-vaccination-schedule','Puppy','Vaccination','Every 2–4 weeks during the primary course',['dog-vaccination-schedule','annual-pet-care-costs'],['adult-dog-booster-schedule','kitten-vaccination-schedule']),
make('dog-worming-schedule','Dog','Worming','Every 3 months for many adult dogs',['annual-pet-care-costs','how-often-worm-cat'],['dog-flea-treatment-schedule','adult-dog-booster-schedule']),
make('adult-dog-booster-schedule','Adult dog','Booster vaccination','Every 1–3 years, depending on vaccine',['dog-vaccination-schedule','annual-pet-care-costs'],['puppy-vaccination-schedule','dog-flea-treatment-schedule']),
make('cat-flea-treatment-schedule','Cat','Flea treatment','Every 30 days for monthly products',['missed-flea-treatment','annual-pet-care-costs'],['cat-worming-schedule','kitten-vaccination-schedule']),
make('kitten-vaccination-schedule','Kitten','Vaccination','Every 3–4 weeks during the primary course',['cat-vaccination-schedule','annual-pet-care-costs'],['cat-worming-schedule','puppy-vaccination-schedule']),
make('cat-worming-schedule','Cat','Worming','Every 3 months for many adult cats',['how-often-worm-cat','cat-vaccination-schedule'],['cat-flea-treatment-schedule','kitten-vaccination-schedule']),
make('rabbit-vaccination-schedule','Rabbit','Vaccination','Every year for many vaccines',['annual-pet-care-costs','cat-vaccination-schedule'],['kitten-vaccination-schedule','adult-dog-booster-schedule']),
];
export const schedule=(slug:string)=>schedules.find(x=>x.slug===slug);
