'use server';
import {admin,supabase} from '@/lib/supabase';import {siteUrl} from '@/lib/env';import {redirect} from 'next/navigation';
export type AuthState={error?:string};
const credentials=(form:FormData)=>({email:String(form.get('email')||'').trim().toLowerCase(),password:String(form.get('password')||'')});
function friendly(message:string){const value=message.toLowerCase();if(value.includes('invalid login credentials'))return 'Wrong email or password — try again or reset it.';if(value.includes('already registered'))return 'That email already has an account. Sign in instead.';if(value.includes('rate limit'))return 'Too many attempts. Wait a moment, then try again.';if(value.includes('password'))return 'Use at least 8 characters for your password.';return 'We could not complete that request. Please try again.'}
export async function login(_:AuthState,form:FormData):Promise<AuthState>{const {email,password}=credentials(form);if(!/^\S+@\S+\.\S+$/.test(email)||!password)return {error:'Enter your email and password.'};const client=await supabase();const {error}=await client.auth.signInWithPassword({email,password});if(error)return {error:friendly(error.message)};redirect('/app')}
export async function signup(_:AuthState,form:FormData):Promise<AuthState>{const {email,password}=credentials(form);if(!/^\S+@\S+\.\S+$/.test(email))return {error:'Enter a valid email address.'};if(password.length<8)return {error:'Use at least 8 characters for your password.'};const client=await supabase();const {data,error}=await client.auth.signUp({email,password});if(error)return {error:friendly(error.message)};if(!data.session){const signedIn=await client.auth.signInWithPassword({email,password});if(signedIn.error)return {error:'Check your inbox to confirm your email, then sign in.'}}if(data.user?.id)await admin().from('app_events').insert({user_id:data.user.id,name:'signup'});redirect('/app/onboarding')}
export async function forgot(_:AuthState,form:FormData):Promise<AuthState>{const email=String(form.get('email')||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return {error:'Enter a valid email address.'};const client=await supabase();const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:`${siteUrl()}/app/reset`});if(error)return {error:friendly(error.message)};return {error:'sent'}}
export async function reset(_:AuthState,form:FormData):Promise<AuthState>{const password=String(form.get('password')||'');if(password.length<8)return {error:'Use at least 8 characters for your password.'};const client=await supabase();const {error}=await client.auth.updateUser({password});if(error)return {error:friendly(error.message)};redirect('/app')}
