'use client'
import { useState } from 'react'

export default function ScanPage() {
  const [proposal, setProposal] = useState<any>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('')
  async function scan(file: File) {
    setBusy(true); setMessage(''); const reader = new FileReader(); reader.onload = async () => { const res = await fetch('/api/ai/scan', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ image: reader.result }) }); const json = await res.json(); setBusy(false); if (!res.ok) setMessage(json.error?.message || "We couldn't read this page — try more light, or add it manually."); else setProposal(json.proposal) }; reader.readAsDataURL(file)
  }
  return <main className="min-h-screen px-6 py-16"><div className="wrap max-w-3xl"><a className="mono" href="/app">← Back to record</a><p className="mono mt-16 text-[var(--health)]">Scan the record</p><h1 className="mt-3 text-5xl">Photograph a booklet or product box.</h1><p className="muted mt-5">We’ll prepare a proposal for you to check. Nothing is saved until you confirm each row.</p><label className="card mt-10 block cursor-pointer p-8 text-center"><span className="mono">{busy ? 'Reading…' : 'Choose one page or photo'}</span><input className="sr-only" type="file" accept="image/*" capture="environment" onChange={e => e.target.files?.[0] && scan(e.target.files[0])} /></label>{message && <p className="mt-5 text-[var(--overdue)]">{message}</p>}{proposal && <section className="card mt-8 p-6"><div className="flex items-center justify-between"><h2 className="text-2xl">Review proposal</h2><span className="mono">CHECK BEFORE SAVING</span></div>{proposal.entries.map((entry:any, i:number)=><div className="ledger-row" key={i}><div><b>{entry.name}</b><p className="mono">{entry.type} · {entry.dateGiven || 'date not found'}{entry.product ? ` · ${entry.product}` : ''}</p></div><span className={`chip ${entry.confidence === 'low' ? 'overdue' : 'health'}`}>{entry.confidence === 'low' ? 'CHECK THIS' : entry.confidence}</span></div>)}<p className="muted mt-5">This is a proposal only. Add each confirmed row through the normal treatment flow.</p><a className="btn mt-5 inline-block" href="/app">Add manually from record →</a></section>}</div></main>
}
