'use client';
import {useMemo,useState} from 'react';import {Logo} from './logo';
const presets=[{type:'flea_tick',name:'Flea & tick',days:30},{type:'worming',name:'Worming',days:90},{type:'heartworm',name:'Heartworm',days:30},{type:'vaccination',name:'Vaccination',days:365},{type:'medication',name:'Medication',days:30},{type:'grooming',name:'Grooming',days:42},{type:'vet_checkup',name:'Vet check-up',days:365}] as const;
const species=[['dog','🐕'],['cat','🐈'],['rabbit','🐇'],['bird','🐦'],['reptile','🦎'],['other','🐾']] as const;
export function Onboarding(){const today=new Date().toISOString().slice(0,10);const [step,setStep]=useState(1);const [name,setName]=useState('');const [kind,setKind]=useState<(typeof species)[number][0]>('dog');const [picked,setPicked]=useState<string[]>(['flea_tick','worming']);const [dates,setDates]=useState<Record<string,string>>({flea_tick:today,worming:today});const [leads,setLeads]=useState([3]);const [email,setEmail]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const selected=useMemo(()=>presets.filter(p=>picked.includes(p.type)),[picked]);
function toggle(type:string){setPicked(v=>v.includes(type)?v.filter(x=>x!==type):[...v,type]);setDates(v=>({...v,[type]:v[type]||today}))}
async function finish(){setBusy(true);setError('');try{const petResult=await fetch('/api/pets',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,species:kind})});const petJson=await petResult.json();if(!petResult.ok)throw new Error(petJson.error?.message||'Your pet could not be saved.');for(const p of selected){const r=await fetch('/api/treatments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({petId:petJson.pet.id,name:p.name,type:p.type,lastGiven:dates[p.type],intervalDays:p.days})});if(!r.ok)throw new Error('A treatment could not be saved. Please try again.')}const pref=await fetch('/api/profile',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({reminderLeads:leads,emailRemindersEnabled:email})});if(!pref.ok)throw new Error('Reminder preferences could not be saved.');location.href=`/app?onboarded=${encodeURIComponent(name)}`}catch(e){setError(e instanceof Error?e.message:'Please try again.');setBusy(false)}}
return <main className="min-h-screen bg-[var(--paper)] px-5 py-8"><div className="mx-auto max-w-2xl"><Logo/><div className="mt-14 flex gap-2" aria-label={`Step ${step} of 3`}>{[1,2,3].map(x=><span key={x} className={`h-2 flex-1 rounded-full ${x<=step?'bg-[var(--health)]':'bg-[var(--rule)]'}`}/>)}</div><p className="mono mt-8 text-[var(--health)]">Step {step} of 3</p>
{step===1&&<section><h1 className="mt-3 text-5xl">Who are we looking after?</h1><label className="mono mt-10 block" htmlFor="pet-name">Their name</label><input autoFocus required id="pet-name" className="rule-input mt-2" value={name} onChange={e=>setName(e.target.value)}/><div className="mt-8 grid grid-cols-3 gap-3">{species.map(([value,icon])=><button key={value} onClick={()=>setKind(value)} className={`card p-4 text-center ${kind===value?'ring-2 ring-[var(--health)]':''}`}><span className="text-3xl">{icon}</span><span className="mono mt-2 block">{value}</span></button>)}</div><button disabled={!name.trim()} className="btn mt-10 w-full" onClick={()=>setStep(2)}>Continue</button></section>}
{step===2&&<section><h1 className="mt-3 text-5xl">Pick their treatments.</h1><p className="muted mt-4">Choose everything you want Tailtend to remember.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{presets.map(p=><div key={p.type} className={`card p-4 ${picked.includes(p.type)?'ring-2 ring-[var(--health)]':''}`}><button className="w-full text-left font-semibold" onClick={()=>toggle(p.type)}>{picked.includes(p.type)?'✓ ':''}{p.name}</button>{picked.includes(p.type)&&<><label className="mono mt-4 block" htmlFor={p.type}>When did you last give this?</label><input id={p.type} type="date" className="rule-input" value={dates[p.type]||today} max={today} onChange={e=>setDates(v=>({...v,[p.type]:e.target.value}))}/></>}</div>)}</div><button disabled={!picked.length} className="btn mt-10 w-full" onClick={()=>setStep(3)}>Continue</button></section>}
{step===3&&<section><h1 className="mt-3 text-5xl">When should we remind you?</h1><p className="muted mt-4">Three days before is selected. Add more if useful.</p><div className="mt-8 flex flex-wrap gap-3">{[7,3,1,0].map(day=><button key={day} onClick={()=>setLeads(v=>v.includes(day)?(v.length>1?v.filter(x=>x!==day):v):[...v,day])} className={`chip px-4 py-3 ${leads.includes(day)?'health':''}`}>{day===0?'Due day':`${day} days`}</button>)}</div><label className="card mt-8 flex items-center justify-between p-5"><span><b>Email reminders</b><span className="muted block text-sm">A quiet heads-up before care is due.</span></span><input type="checkbox" checked={email} onChange={e=>setEmail(e.target.checked)} className="h-5 w-5"/></label>{error&&<p role="alert" className="mt-5 border-l-2 border-[var(--stamp)] pl-3">{error}</p>}<button disabled={busy} className="btn mt-10 w-full" onClick={finish}>{busy?'Building the record…':'Start the record'}</button></section>}</div></main>}
