'use client';import {useEffect,useState} from 'react';
export type PaywallTrigger='second_pet'|'sitter_share'|'vet_share'|'vet_report'|'weight_trend'|'eu_travel'|'household'|'ai_copilot'|'calendar';
const headlines:Record<PaywallTrigger,(name:string)=>string>={
second_pet:name=>`${name} deserves a record too.`,
sitter_share:name=>`Share ${name} with your sitter.`,
vet_share:name=>`Give the vet ${name}'s clinical record.`,
vet_report:name=>`Get ${name}'s vet-visit sheet.`,
weight_trend:name=>`See ${name}'s weight trend.`,
eu_travel:name=>`Check ${name}'s EU travel papers.`,
household:name=>`Bring the whole household into ${name}'s record.`,
ai_copilot:name=>`Ask anything about ${name}'s care.`,
calendar:name=>`${name}'s dates, in your calendar.`
};
const features=['AI copilot','Caretaker & sitter sharing','Vet report + sitter handover PDF','Weight tracking + trend chart','Cost tracking + insurance CSV','EU travel check','Unlimited photos & pets'];
export function PaywallSheet({trigger,petName,onClose}:{trigger:PaywallTrigger;petName?:string;onClose:()=>void}){const [plan,setPlan]=useState<'yearly'|'monthly'>('yearly');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [founding,setFounding]=useState<{founding:boolean;claimed:number}|null>(null);const headline=headlines[trigger](petName||'your pet');useEffect(()=>{fetch('/api/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'paywall_viewed',metadata:{trigger}})});fetch('/api/stripe/plans').then(r=>r.json()).then(setFounding).catch(()=>{})},[trigger]);async function checkout(){setBusy(true);setError('');try{const r=await fetch('/api/stripe/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({plan,trigger})});const j=await r.json() as {url?:string};if(j.url)location.href=j.url;else throw new Error('unavailable')}catch{setError('Secure checkout could not open just yet — please try again in a moment.')}finally{setBusy(false)}}return <div className="fixed inset-0 z-50 grid place-items-end bg-[rgba(34,48,60,.38)] p-3 sm:place-items-center" role="dialog" aria-modal="true" aria-labelledby="paywall-title"><section className="card max-h-[94vh] w-full max-w-xl overflow-auto p-7 sm:p-9"><p className="mono text-[var(--health)]">Tailtend Premium</p><h2 id="paywall-title" className="mt-3 text-4xl">{headline}</h2><div className="mt-7 border-t border-[var(--rule)]">{features.map(x=><div className="ledger-row" key={x}><span>{x}</span><span className="text-[var(--health)]">✓</span></div>)}</div><div className="mt-7 grid gap-3 sm:grid-cols-2"><button onClick={()=>setPlan('yearly')} className={`card p-4 text-left ${plan==='yearly'?'ring-2 ring-[var(--health)]':''}`}><b>{founding?.founding?'Founding price €7,99 / year':'€9,99 / year'}</b><span className="mono mt-2 block text-[var(--health)]">{founding?.founding?`${founding.claimed} of 100 claimed`:'2 months free vs monthly'}</span>{founding?.founding&&<span className="muted mt-2 block text-xs">First 100 members, then €9,99</span>}</button><button onClick={()=>setPlan('monthly')} className={`card p-4 text-left ${plan==='monthly'?'ring-2 ring-[var(--health)]':''}`}><b>€4,99 / month</b><span className="muted mt-2 block text-sm">Flexible monthly plan</span></button></div><p className="mono mt-6 text-center">Cancel anytime · access until period end</p>{error&&<p role="alert" className="mt-4 border-l-2 border-[var(--stamp)] pl-3 text-sm">{error}</p>}<button onClick={checkout} disabled={busy} className="btn mt-5 w-full">{busy?'Opening secure checkout…':'Continue to secure checkout'}</button><p className="mt-3 text-center text-xs text-[var(--ink-60)]">By continuing you agree to the <a className="underline" href="/terms">Terms</a>.</p><button onClick={onClose} className="mt-4 w-full py-2 text-sm">Maybe later</button></section></div>}
